"""
ERIS v5 — Platonic Cognitive Bridge
=====================================
Orchestrates the full Claude → Zombie → Claude pipeline.

Pipeline
---------
The three modes map to different subsets of the same stage sequence:

  ``passive``      :  encode → analyze → [decode]
  ``analyze_only`` :  encode → analyze
  ``ruminate``     :  encode → analyze(pre) → think(N steps) → analyze(post) → [decode]

In ``ruminate`` mode the pre-analysis runs on the hidden state immediately after
encoding (the zombie's first impression of the text).  The post-analysis runs on
the final hidden state after the latent rollout (what the zombie has "settled on").
Implicit features are computed from the **post** hidden state vs the surface text —
they represent concepts that emerged during rumination but were never written.

Design constraints
-------------------
- The bridge manages a **temporary session** by default.  Pass ``session_id`` to
  reuse an existing session (useful for multi-turn conversations).
- Analyzer calls follow the device rules established in ``analyzers.py``:
  Pattern A (inline, GPU) for Â-hat during the rollout; Pattern B (CPU→GPU
  re-upload) for SAE post-hoc analysis via ``registry.run(..., inference_device)``.
- The bridge is **stateless** between calls — no internal session cache.

Usage::

    from engine import LatentRelayEngine
    from eris.config import ERISConfig
    from eris.analyzers import AnalyzerRegistry
    from eris.bridge import ERISBridge

    engine = LatentRelayEngine("Qwen/Qwen3-14B")
    cfg    = ERISConfig.load()
    registry = AnalyzerRegistry.from_config(cfg)
    bridge = ERISBridge(engine, registry)

    result = bridge.run(
        claude_text  = "What are the risks of a distributed lock?",
        mode         = "ruminate",
        n_steps      = 60,
        analyses     = ["sae_features", "a_hat", "token_norms"],
        decode_after = True,
        max_new_tokens = 256,
    )
    print(result["enriched_text"])
    print(result["analysis"]["implicit_features"])
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any

import torch

from eris.implicit_features import find_implicit_features


# ── Valid modes ────────────────────────────────────────────────────────────────

_VALID_MODES = {"passive", "ruminate", "analyze_only"}


# ── Result dataclass ──────────────────────────────────────────────────────────

@dataclass
class BridgeResult:
    """
    Full output of a single bridge run.

    Attributes:
        mode:               The mode that was executed.
        enriched_text:      Text generated by the zombie after rumination, or
                            None if ``decode_after=False`` or mode is
                            ``analyze_only``.
        analysis:           Dict of analysis results (sae_features, a_hat_score,
                            cosine_map, token_norms, implicit_features).
        trajectory_summary: Summary of the latent rollout trajectory, or None
                            if mode is not ``ruminate``.
        pre_analysis:       Analysis of the encoded hidden state (before rollout),
                            only populated in ``ruminate`` mode.
        tokens:             Subword tokens of the input text.
        elapsed_s:          Total wall-clock time in seconds.
        handles:            Dict of internal thought handles created during the run.
    """
    mode: str
    enriched_text: Optional[str]
    analysis: Dict[str, Any]
    trajectory_summary: Optional[Dict]
    pre_analysis: Optional[Dict]
    tokens: List[str]
    elapsed_s: float
    handles: Dict[str, str] = field(default_factory=dict)

    def to_dict(self) -> Dict:
        return {
            "enriched_text":      self.enriched_text,
            "analysis":           self.analysis,
            "trajectory_summary": self.trajectory_summary,
            "pre_analysis":       self.pre_analysis,
            "tokens":             self.tokens,
            "elapsed_s":          round(self.elapsed_s, 3),
            "handles":            self.handles,
        }


# ── Bridge ────────────────────────────────────────────────────────────────────

class ERISBridge:
    """
    Orchestrates the encode → analyze → think → decode pipeline.

    Args:
        engine:   A loaded :class:`~engine.LatentRelayEngine` instance.
        registry: An :class:`~eris.analyzers.AnalyzerRegistry` instance.
                  Can be an empty registry (all analyzers None) — the bridge
                  will return null analysis fields without crashing.
    """

    def __init__(self, engine, registry) -> None:
        self.engine   = engine
        self.registry = registry

    # ── Main entry point ──────────────────────────────────────────────────────

    def run(
        self,
        claude_text: str,
        *,
        mode: str = "passive",
        n_steps: int = 60,
        analyses: Optional[List[str]] = None,
        decode_after: bool = True,
        max_new_tokens: int = 512,
        temperature: float = 0.6,
        top_p: float = 0.95,
        session_id: Optional[str] = None,
        implicit_min_activation: float = 0.0,
        implicit_match_mode: str = "any",
    ) -> BridgeResult:
        """
        Run the full Claude → Zombie → Claude bridge pipeline.

        Args:
            claude_text:  Text input from Claude (or any source).
            mode:         ``"passive"``, ``"ruminate"``, or ``"analyze_only"``.
            n_steps:      Latent rollout steps (``ruminate`` only).
            analyses:     List of analyses to run.  Defaults to
                          ``["sae_features", "a_hat", "token_norms"]``.
            decode_after: Generate text after the pipeline (ignored in
                          ``analyze_only`` mode).
            max_new_tokens: Token budget for the generated response.
            temperature:  Sampling temperature.
            top_p:        Nucleus sampling p.
            session_id:   Reuse an existing session.  If None, a temporary
                          session is created and deleted after the run.
            implicit_min_activation: Minimum activation for implicit feature
                          detection.
            implicit_match_mode: ``"any"`` or ``"all"`` — see
                          :func:`~eris.implicit_features.find_implicit_features`.

        Returns:
            :class:`BridgeResult` with all populated fields.

        Raises:
            ValueError: If ``mode`` is not one of the valid values.

        Example curl (via eris_server.py)::

            curl -X POST http://localhost:8001/v1/bridge \\
              -H 'Content-Type: application/json' \\
              -d '{
                "claude_text": "What are the risks of distributed locking?",
                "mode": "ruminate",
                "n_steps": 60,
                "analyses": ["sae_features", "a_hat", "token_norms"],
                "decode_after": true,
                "max_new_tokens": 256
              }'
        """
        if mode not in _VALID_MODES:
            raise ValueError(
                f"Invalid mode '{mode}'. Expected one of {sorted(_VALID_MODES)}."
            )
        if analyses is None:
            analyses = ["sae_features", "a_hat", "token_norms"]

        t0 = time.time()
        owns_session = session_id is None
        handles: Dict[str, str] = {}

        try:
            # ── Session ───────────────────────────────────────────────────────
            if owns_session:
                session_id = self.engine.create_session()

            # ── Stage 1: Encode ───────────────────────────────────────────────
            enc_result = self.engine.encode(
                claude_text,
                return_layers=[-1],
                session_id=session_id,
            )
            enc_handle: Optional[str] = enc_result["handle"]
            tokens: List[str]         = enc_result["tokens"]
            if enc_handle:
                handles["encode"] = enc_handle

            # Retrieve the last-layer hidden state (CPU float32) for analysis.
            # enc_handle is populated because we passed session_id.
            pre_hidden = self._get_hidden(session_id, enc_handle)

            # ── Stage 2: Pre-analysis ─────────────────────────────────────────
            pre_analysis = self._run_analysis(pre_hidden, analyses)

            # ── Stage 3: Latent rollout (ruminate only) ───────────────────────
            think_result:        Optional[Dict]  = None
            post_hidden:         Optional[torch.Tensor] = None
            trajectory_summary:  Optional[Dict]  = None

            if mode == "ruminate":
                a_hat_fn = (
                    self.registry.a_hat.as_callback()
                    if self.registry.a_hat is not None
                    else None
                )
                think_result = self.engine.think(
                    session_id,
                    claude_text,
                    n_steps=n_steps,
                    role="ruminate",
                    return_trajectory=True,
                    a_hat_fn=a_hat_fn,
                )
                handles["think"] = think_result["handle"]

                # Retrieve the post-rollout hidden state for post-analysis.
                post_hidden = self._get_hidden(
                    session_id, think_result["handle"]
                )

                # Build trajectory summary from think() output.
                trajectory_summary = {
                    "total_displacement": think_result.get("total_displacement", 0.0),
                    "max_a_hat":          _max_a_hat(think_result.get("trajectory", [])),
                    "steps_to_convergence": _steps_to_convergence(
                        think_result.get("trajectory", [])
                    ),
                    "n_steps":            think_result.get("n_steps", n_steps),
                }

            # ── Stage 4: Post-analysis ────────────────────────────────────────
            # In passive/analyze_only: post-analysis IS the pre-analysis.
            analysis_hidden = post_hidden if post_hidden is not None else pre_hidden
            post_analysis   = self._run_analysis(analysis_hidden, analyses)

            # Implicit features: compare post-analysis SAE features vs surface text.
            post_analysis["implicit_features"] = find_implicit_features(
                post_analysis.get("sae_features"),
                tokens,
                min_activation=implicit_min_activation,
                match_mode=implicit_match_mode,
            )

            # ── Stage 5: Decode ───────────────────────────────────────────────
            enriched_text: Optional[str] = None
            if decode_after and mode != "analyze_only":
                decode_handle = handles.get("think") or handles.get("encode")
                collab = self.engine.collaborate(
                    session_id,
                    [decode_handle] if decode_handle else [],
                    claude_text,
                    max_new_tokens=max_new_tokens,
                    temperature=temperature,
                    top_p=top_p,
                )
                enriched_text = collab["text"]

            elapsed = time.time() - t0

            return BridgeResult(
                mode=mode,
                enriched_text=enriched_text,
                analysis=post_analysis,
                trajectory_summary=trajectory_summary,
                pre_analysis=pre_analysis if mode == "ruminate" else None,
                tokens=tokens,
                elapsed_s=elapsed,
                handles=handles,
            )

        finally:
            # Clean up the temporary session to free GPU memory.
            if owns_session and session_id is not None:
                self.engine.delete_session(session_id)

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _get_hidden(
        self, session_id: str, handle: Optional[str]
    ) -> Optional[torch.Tensor]:
        """
        Retrieve the last-layer hidden state from a stored thought.

        Returns a CPU float32 tensor of shape ``[1, hidden_dim]``, or None if
        the handle is not found.
        """
        if handle is None:
            return None
        info = self.engine.get_thought_info(session_id, handle)
        if info is None:
            return None
        # Access the live thought object to get the tensor.
        with self.engine._lock:
            session = self.engine._sessions.get(session_id)
            if session is None:
                return None
            thought = session.thoughts.get(handle)
            if thought is None or thought.hidden_embedding is None:
                return None
            return thought.hidden_embedding.detach().cpu().float()

    def _run_analysis(
        self,
        hidden: Optional[torch.Tensor],
        analyses: List[str],
    ) -> Dict:
        """
        Run the registry analyzers on a hidden state.

        Uses Pattern B: hidden is on CPU (from ``_get_hidden``), and we
        re-upload to the engine device for GPU-bound analyzers.
        """
        if hidden is None:
            return {name: None for name in analyses}

        return self.registry.run(
            hidden,
            analyses,
            inference_device=self.engine.device,
        )


# ── Trajectory helpers (pure functions) ───────────────────────────────────────

def _max_a_hat(trajectory: List[Dict]) -> Optional[float]:
    """Peak Â-hat score across all trajectory steps."""
    scores = [
        s["a_hat"] for s in trajectory
        if s.get("a_hat") is not None
    ]
    return round(max(scores), 4) if scores else None


def _steps_to_convergence(trajectory: List[Dict], threshold_frac: float = 0.01) -> Optional[int]:
    """
    Estimate the step at which displacement stopped growing significantly.

    Mirrors :meth:`~eris.trajectory.TrajectoryTracker.steps_to_convergence`
    but operates on the serialised trajectory list returned by ``think()``.
    """
    if len(trajectory) < 2:
        return None
    total = trajectory[-1].get("displacement", 0.0)
    if total < 1e-6:
        return None
    threshold = threshold_frac * total
    last_significant = 0
    for i in range(1, len(trajectory)):
        d_prev = trajectory[i - 1].get("displacement", 0.0)
        d_curr = trajectory[i].get("displacement", 0.0)
        if (d_curr - d_prev) > threshold:
            last_significant = i
    return last_significant
